language: ruby
rvm:
  - 2.1.2

before_install:
  - gem update --system
  - gem --version

script:
    - bundle install
    - bundle exec rspec
    - bundle exec cucumber

# whitelist
branches:
  only:
    - develop
